### ISSUE TITLE
L Series fan no longer works.

### ISSUE THREAD

**Issue by tkhan456** [mikelawrence/senseme-hacs#1]
> Logger: custom_components.senseme.fan
Source: custom_components/senseme/fan.py:43 
First occurred: 4:25:36 PM (2 occurrences) 
Last logged: 4:31:33 PM

>Discovered unknown SenseME device model='FAN,LSERIES'

Older version of this integration worked with all 3 of my fanes.  One of them is an L-series fan. L-The new integration will not discover it.  Is this on purpose?  Can the L-series fan be added to work?

**Comment by mikelawrence** [comment]
Well I really should have added unknown models like before but instead I ignored them. What I wanted was to get feedback from users of this integration. I need model names as reported by the fan for those devices I don't have. 

So version 2.0.1 of this component added the L-Series fan (thanks BTW). And it now adds unknown model fans while producing a warning that hopefully people will give me feedback so I can collect a list of model names.

**Comment by tkhan456** [comment]
Awesome and thank you for this excellent integration.  Updated and works!

**Comment by mikelawrence** [comment]
So release v2.0.1 did not add the light and occupancy sensor either. Release v2.0.2 adds them back. When you get a moment check the light and occupancy sensor out after installing v2.0.2.

**Comment by tkhan456** [comment]
looks like it's working.  cheers

**Comment by mikelawrence** [comment]
Glad it works. Thanks for the feedback!

**Comment by mikelawrence** [comment]
@tkhan456 I was hoping you could help me out debugging a possible issue with L-Series Haiku fans and standalone Haiku lights.
I have a parameter listing from a Haiku L-Series Fan with an associated Wireless Wall Controller. What I need is a parameter listing from a Haiku L-Series Fan WITHOUT a Wireless Wall Controller. If you don't have a Wireless Wall Controller would you please add the following to your configuration yaml and post the log results after rebooting your Home Assistant instance?

```
logger:
  default: warning
  logs:
    custom_components.senseme: debug
    aiosenseme: debug
```

**Comment by tkhan456** [comment]
Sorry for the delay.  I'll give it a shot today and post the log soon.

**Comment by tkhan456** [comment]
Here you go.  I redacted some personal info.  Sorry if that causes issues for you.
[home-assistant-redacted-2.log](https://github.com/mikelawrence/senseme-hacs/files/4852790/home-assistant-redacted-2.log)

**Comment by mikelawrence** [comment]
Thanks for the log! It's exactly what I needed and your redactions don't impact me.
