### ISSUE TITLE
Always receiving "No SenseME devices found on the network."

### ISSUE THREAD

**Issue by dethpickle** [mikelawrence/senseme-hacs#12]
I see the note that sometimes the fan doesn't show up and you have to try multiple times.  I've never been able to get even initial install of the integration because when I try, it gives the "No SenseME devices found on the network." message and doesn't install.  I don't see anything in the HA logs.  I've tried uninstalling and reinstalling the integration from HACS.

I'm running Hassio from a VMware vm.  v112.4 with everything current.
I have a Haiku-L that has been setup with the Haiku by BAF iOS app.  Amazon Echo is setup and working with it.
Fan shows firmware 2.6.1

Are there any caveats with what network is being scanned?  My HASSio is on a 10.1.2.x subnet and the fan is on wifi on a 172.16.1 subnet.  There are no network rules to drop traffic between them and other devices have been detected by HA without issue.  I don't really suspect this, but without any other leads from logs - just nothing showing up - I'm a bit at a loss for places to look.

Any suggestions?  And, is it the correct behavior that the Integration doesn't install (to HA Integrations, not from HACS) until there is a first device to be detected?

Thanks!

**Comment by mikelawrence** [comment]
Senseme fans use a simple broadcast/response discovery mechanism. Broadcasts are specific to local networks and by default are dropped between networks. So this component will only work when the fan and Home Assistant are on the same network. There may be some router finesse that will make this work with your network but that's hardware specific and beyond my help.  

Have you tried adding a fan that is already on the other network using the BAF app? I have a feeling it may not be discovered for the same reason.

I have thought about allowing manual IP address entry in addition to discovery for people like you but I haven't done this yet. This might also ease the problem with discovery not finding fans on startup.

**Comment by dethpickle** [comment]
Thanks, Mike.  That's a good clue and I'll try to see if I can finagle it around to the same network.  Manual IP would be nice, both for me and for the dropouts you've mentioned.

I'll try to work with what you have now though.  My issue is that I maintain separate networks and vlans for IoT stuff as well as my collection of VMs and normal personal devices for people here.  I'll just try to move the fan over to the same network as HA and see if that helps (and will report back).

Thanks again!

**Comment by mikelawrence** [comment]
Ya I have a separate IoT VLAN at my house and have the same problem. So my fans are on the same network as HA.

When I have more time I will look at making changes to support manual IP entry.

**Comment by dethpickle** [comment]
So far, I haven't been successful at getting a fixed DHCP device on my wifi to allocate to a different subnet and so haven't been able to get this to work.  Obviously, that's my issue and I'll continue to work on it.

I'm going to close this and either keep trying on the networking side and/or waiting for a new feature of manual IP entry.  Since this is all in your spare time, I'll keep no expectations.  I appreciate your work like all the others that have contributed to make HA the fun project it is.

Thanks!

Dave
