### ISSUE TITLE
Why not make it official?

### ISSUE THREAD

**Issue by kylekampy** [mikelawrence/senseme-hacs#13]
Hi all!

I've been using the senseme custom components for over a year now and I am incredibly grateful to those of you that have worked on it. It's incredibly reliable (compared to other custom components I've used) and I'm very appreciative.

Sorry for raising an issue for this, but Github doesn't currently seem to have a better way to start a discussion.

My question is this: is there a particular reason not to pursue making this an official Home Assistant component and get merged into the root repo? There's a recent PR for Haiku support that looks relatively incomplete compared to this unofficial senseme alternative: https://github.com/home-assistant/core/pull/38108

Just trying to understand. I'd be happy to put in some effort in making an official PR over there if there is interest, but my assumption is that it must not be wanted for some reason.

Thanks! :)

**Comment by mikelawrence** [comment]
I have no reason not to other than I don't really consider myself a professional coder. From what I have seen there can be a bit work to get a new integration accepted so I'd be more than willing to let you handle the PR. ;)

josh-codes posted his intent to work on a Senseme component in this [thread](https://community.home-assistant.io/t/haiku-senseme-smart-fan-support/4702/68?u=lawr1000). This is the same thread I've been posting too about this integration.

**Comment by kylekampy** [comment]
Thanks for your reply, @mikelawrence. I'm definitely no pro when it comes to python, but I will see what I can do to pitch in with that josh-codes PR!

I'll follow along on that discussion you linked to and marked this as closed. Thanks again!

**Comment by mikelawrence** [comment]
I wasn't saying no and definitely not saying go with josh-codes PR. Getting an integration into Home Assistant is a step up from what I have been doing. They have a whole development flow and requirements that are more stringent than I'm used to. 

This integration at lease follows one of HA's developer key tenets which is "All communication to external devices or services must be wrapped in an external Python library hosted on pypi." 

However, I am concerned about the lack of support for the newer BAF fans like the i6.

**Comment by ghost** [comment]
I have light support in my Pypi I just did not add it to Home Assistant because I am still testing it.

**Comment by bdraco** [comment]
If someone decides to move this forward with a PR to core and you need a code review feel free to ping me.

**Comment by bdraco** [comment]
The fan speed issue is likely going to be a blocker though until these get finished:

https://github.com/home-assistant/architecture/issues/127
https://github.com/home-assistant/core/pull/39204

**Comment by bdraco** [comment]
Fan speed issue should not longer be a blocker in `2021.3` since https://github.com/home-assistant/core/pull/45407 is merged

**Comment by mikelawrence** [comment]
I opened a [PR](https://github.com/home-assistant/core/pull/62901) with HA and bdraco picked it up right away. He will eventually fold this integration into HA itself.
