### ISSUE TITLE
working on the current HA?

### ISSUE THREAD

**Issue by styygeli** [mikelawrence/senseme-hacs#17]
Just installed this via HACS, rebooted the raspi with ha on it, went to the configuration - integrations - add integration and then tried to search for the senseme but it doesn't appear at all.

```Core
Version
core-2021.1.4

Operating System
Home Assistant OS 5.10
```

**Comment by claytonjn** [comment]
You mean that SenseME doesn't show up as an integration? You probably need to clear browser cache or try a different browser if that is the case.

**Comment by styygeli** [comment]
Yeah that's what I meant, and that was the issue too :)

Had to switch to smartphone browser to get it show up, now shows up on desktop too. Thanks a lot :)
