### ISSUE TITLE
Enable manual fan addition

### ISSUE THREAD

**Issue by bbqluke** [mikelawrence/senseme-hacs#19]
My fans are running on a separate IOT VLAN to my Home Assistant. Is it possible to add a feature to manually define the IP address of a fan, rather that broadcast discovery, as this does not work with complex networks?

**Comment by mikelawrence** [comment]
Ya I keep my fans on my main network instead of my IOT network for this reason. I have been thinking about a solution for this and it may be possible. Right now my fans are down and I can't look at this right away so give me a bit of time.

**Comment by mikelawrence** [comment]
Just giving a quick update. I have aiosenseme library working by IP Address instead of discover first. I'm now on working integrating the new library with the senseme-hacs HA integration.

**Comment by mikelawrence** [comment]
The new library and senseme integration are shaping up nicely. Look for a release soon after HA 2021.3 comes out.

**Comment by mikelawrence** [comment]
v2.2.0 of this integration has been released and it supports adding SenseME devices by manual IP address. There is one caveat, this new version requires Home Assistant 2021.3 which is due to be released in a few days.

**Comment by bbqluke** [comment]
Thanks Mike, really appreciated!

**Comment by mikelawrence** [comment]
Now that v2.2.1 of this component has been released this issue is fixed.
