### ISSUE TITLE
Version Check Error

### ISSUE THREAD

**Issue by ridizy** [mikelawrence/senseme-hacs#26]
## Version of the custom_component

v2.2.0

## Describe the bug
When installing through HACS, installation is blocked with the following error:
```You are running Home Assistant version '2021.3.0', but this repository requires minimum version '2021.3' to be installed.```

**Comment by mikelawrence** [comment]
I've update the hacs.json file but I may need to redo the release. Try again and see if it's better on your end. I will try on my Home Assistant.

**Comment by ridizy** [comment]
Thanks for the quick update!  But yes, may need a release as I'm still getting the error

**Comment by mikelawrence** [comment]
I re-released the same version v2.2.0. Should work correctly now.

**Comment by ridizy** [comment]
That did it.  Thank you!

**Comment by yieldhog** [comment]
Hi @mikelawrence love the integration. I've had it installed for awhile through HACS. It looks like my version installed is 2.1.3 and I haven't gotten any prompts to update like I normally do w/ HACS. Any thoughts on what I can do here? Thanks

**Comment by yieldhog** [comment]
@mikelawrence sorry, I see that it was a function of my older Home Assistant installed version. Updated now.

**Comment by mikelawrence** [comment]
Yes you are right and for the record; as of sensme-hacs v2.2.0, Home Assistant 2021.3.0 and above is required.

Glad you figured it out!
