### ISSUE TITLE
Fan speed no longer showing up on Lovelace dashboard

### ISSUE THREAD

**Issue by quadhammer** [mikelawrence/senseme-hacs#29]
I used to use this following code to display a fan speed, but after the latest update it reports the speed as 'none'.  Can anyone see what I'm doing wrong, please?

```
color: auto-no-temperature
entity: fan.south_fan
hold_action:
  action: more-info
icon: 'mdi:fan'
label: |
  [[[
    if (entity.state == 'off') return 'Off';
    else return entity.attributes['speed'] + '/7';
  ]]]
name: South Fan
show_label: true
state:
  - value: 'on'
    spin: true
type: 'custom:button-card'
```

**Comment by mikelawrence** [comment]
As of Home Assistant 2021.3.0 the fan model has changed and speeds are now percentages. Below is a list of attributes on one of my fans. There is now a percentage and percentage_step. Notice that 100.0 / percentage_step is 7 and percentage / percentage_step is 2.94. You can round this to get your answer of 3.

I'm guessing there are others that are having problems like this. You might be better off asking this question on the HA forums.

![image](https://user-images.githubusercontent.com/5221530/110117665-ccc8e000-7d7e-11eb-9529-66fc6e307133.png)

**Comment by quadhammer** [comment]
Using senseme 2.2.2 and home Assistant core core-2021.3.2 it is now displaying properly as low medium and high. I just had to delete the little seven on the end:

```
color: auto-no-temperature
entity: fan.south_fan_2
hold_action:
  action: more-info
icon: 'mdi:fan'
label: |
  [[[
    if (entity.state == 'off') return 'Off';
    else return entity.attributes['speed'];
  ]]]
name: South Fan
show_label: true
state:
  - value: 'on'
    spin: true
type: 'custom:button-card'
```

Thank you for your help, and your work on the plug-in. It's great.

Now I just need to discover howto make low medium and high in upper case. :)

**Comment by mikelawrence** [comment]
I haven't done any work in Lovelace but I'm guessing that code is javascript so try this:

`else return entity.attributes['speed'].toUpperCase();`
