### ISSUE TITLE
service: fan.set_speed not working for sending 'low'

### ISSUE THREAD

**Issue by quadhammer** [mikelawrence/senseme-hacs#30]
I was having trouble designing a card for various speeds, but I think it may be something a bit lower level. When I use the developer page to send a speed of low, it's showing up as medium. I can send medium and high to change things, but just not low.

Here's a picture of the issue, in case am doing something wrong:
https://imgur.com/a/ZFvcPWH

Thank you

**Comment by bdraco** [comment]
set_speed is deprecated in Home Assistant.  

Check for the percentage_step in the attributes to determine the speed steps and call set_percentage instead
