### ISSUE TITLE
Cannot find Fan after Firmware Update

### ISSUE THREAD

**Issue by Ace0510** [mikelawrence/senseme-hacs#43]
After updating to Firmware version 3.0.0, Sense Me cannot find the address which has been reserved via the router

**Comment by mbrennan** [comment]
I'm having the same issue.  The latest firmware update along with the new app seems to have completely killed access to the fans through this integration.

**Comment by SuddenlyEngineer** [comment]
Had a chat with BAF support. The (currently optional) firmware upgrade for the Haikus will use the i6 BAF app to communicate. I have not upgraded my fans, but they are currently planning for a forced upgrade in the fall. They have confirmed that the RTI and Control4 integrations will break with this change, and I think all of them (and this integration) use the same library. @mikelawrence I can't find the i6-test branch, but it would be worth testing for these guys if you could make it public.

**Comment by bdraco** [comment]
This issue is being tracked here https://github.com/home-assistant/core/issues/69370 along with downgrade instructions
